### ISSUE TITLE
All code should pass through a linter

### ISSUE THREAD

**Issue by olleharstedt** [deathraygames/civ-clicker#43]
Don't know which linter is best right now for Javascript. Any ideas?

**Comment by olleharstedt** [comment]
Maybe ESHint? https://www.sitepoint.com/comparison-javascript-linting-tools/

**Comment by olleharstedt** [comment]
http://eslint.org/docs/user-guide/getting-started

**Comment by olleharstedt** [comment]
Flow from Facebook can also be used. It can detect bugs that a linter will not. It requires the line

```javascript
/* @flow */
```

at the top of each file.

**Comment by Anahkiasen** [comment]
From my experience they're not exclusive, Flow and ESLint go hand in hand although you can configure ESLint to also lint your codebase with Flow through [this plugin](https://www.npmjs.com/package/eslint-plugin-flowtype-errors).

From personal experience both are amazing tools, and Flow allows you to introduce static types to your codebase gradually (instead of all at once like with Typescript). I'd maybe recommend to start with ESlint using the "recommended" ruleset that comes with it, and go from there.

**Comment by olleharstedt** [comment]
Yes, I think that's a good idea, too.

**Comment by Lukenickerson** [comment]
I added in eslint as a dev dependency, and updated the linting rules to my favorite: airbnb-base with some modifications.
