### ISSUE TITLE
Happyness of people

### ISSUE THREAD

**Issue by Giovani93** [deathraygames/civ-clicker#68]
Hello.
My name is Marco Oros. I have a little request to You, because happyness isn't view good to me, I am blind user of this game. I use this game with keyboard and screen reader.
Please, could You edit It for example, like this:
Happyness: Content
Happyness: Unhappy
Happyness: Angry
Is It possible to rewrite It, or not?
Thank You.
Best regards
Marco Oros

**Comment by Lukenickerson** [comment]
Hi Marco. I've made a change that I believe should fix the problem with happiness and the screen reader. The fix is in the cutting-edge branch available at https://deathraygames.github.io/civ-clicker/. Please let me know if there are any other screen-reader issues as I'd like to make sure the game is usable by the blind.
